### ISSUE TITLE
Which model is running in the demo video?

### ISSUE THREAD

**Issue by iuhiyuh** [Thinklab-SJTU/Bench2Drive#18]
I've noticed that the demo video features overtaking, but with the VAD pth file you released, it keeps waiting in the same scenario.

**Comment by iuhiyuh** [comment]
In addition, I have noticed the following issues:

The frame rate of Carla I'm running is very low.
The saved images do not have the guidance lines output as seen in the demo.
At intersections, there is a high probability that the vehicle will stop, causing the "RouteCompletionTest" and "AgentBlockedTest" to fail.
Could you please provide any suggestions?

**Comment by jiaxiaosong1002** [comment]
@iuhiyuh  The demo recorded the behaviors of our expert model Think2Drive.  Other baselines may not have such strong capability.

1.  Running CARLA with rendering is naturally computational intensive and thus slow, which is why we need multi-gpu eval.
2.  You need to use visualization code to process your log.
3.  We prepare the benchmark to allow the community to explore how to solve these scenarios. Thus, it is natural that current models do not have such capability.
