### ISSUE TITLE
Question about lidar points data.

### ISSUE THREAD

**Issue by weimengchuan** [Thinklab-SJTU/Bench2Drive#24]
I find there are no intensity in lidar points data. Do you have a plan to supplement them?

**Comment by jiaxiaosong1002** [comment]
@weimengchuan  Unfortunately, no. For compression, we have not stored that.

**Comment by jayyoung0802** [comment]
Hi, Carla generate 3D points without intensity. Since this is a simulated Lidar all the points are perfect, all of them would have same intensity. [refer](https://github.com/carla-simulator/carla/issues/327#issuecomment-378592765)

And,  you can simply calculate based on the atmosphere attenuation ratio, 

> attenuation_rate=0.004   
> dist = np.sqrt(data['x']**2 + data["y"]**2 + data["z"]**2)
> intensity_loss = np.exp(-attenuation_rate * dist)

It refer to [link](https://github.com/carla-simulator/carla/issues/327#issuecomment-1820707111).

**Comment by weimengchuan** [comment]
Thanks!
