### ISSUE TITLE
Question about x_command_far and y_command_far.

### ISSUE THREAD

**Issue by weimengchuan** [Thinklab-SJTU/Bench2Drive#25]
Hi, I wonder know the definition of x_command_far and y_command_far? Is it the ego location in the next several frames? If so, how many frames?

Thans in advance!

**Comment by jiaxiaosong1002** [comment]
@weimengchuan Hi, it's the goal point. Please refer to https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/tools/data_collect.py for more details.  You may also run models in Bench2DriveZoo to check these two points.

**Comment by zhanghui75** [comment]
I wonder how this goal point is generated.  I checked data_collect.py, and found that it is from self._global_plan (line 718).

So, is this self._global_plan generated by calling set_global_plan() function in Bench2Drive-main\leaderboard\leaderboard\autoagents\autonomous_agent.py, and the distance from neighboring goal points are 50 meters due to the line 130 (ds_ids = downsample_route(global_plan_world_coord, 50))?

**Comment by robosuite** [comment]
@jiaxiaosong1002 would you mind kindly answer the question? how is command_far collected in data_collect.py, is it the last point in self._route_planner.route?

**Comment by jayyoung0802** [comment]
Hi @robosuite , it's available, refer to [#issue 34](https://github.com/Thinklab-SJTU/Bench2DriveZoo/issues/34).
