### ISSUE TITLE
Inquiry on Route and Scenario Generation Process

### ISSUE THREAD

**Issue by haibao-yu** [Thinklab-SJTU/Bench2Drive#26]
Hi, all:

Thank you for your outstanding work in comprehensively evaluating the end-to-end autonomous driving system using a closed-loop approach. I am curious about the methods you use to obtain the routes and traffic scenarios for generating the clips. Could you provide detailed information on the generation process?

Hope to receive your reply!

Best regards

**Comment by jiaxiaosong1002** [comment]
@haibao-yu Thanks for your interests. Unfortunately, no. We do not plan to the expert related code.

**Comment by exiawsh** [comment]
@jiaxiaosong1002 Hi, could you please share some details about the expert. Is the expert a rule-based model or RL agent (e.g. ,roach, think2drive)? Because the quality of the expert is important.

**Comment by exiawsh** [comment]
I also noticed that you mentioned PDM-lite. Are the results from the same b2d test set? Because the Driving score in PDM-lite is so high.
![image](https://github.com/user-attachments/assets/e118ae50-a85e-4ae3-b6ba-47def5ebb981)
![image](https://github.com/user-attachments/assets/c86a3983-e465-474c-abdf-826937f4bfcd)

**Comment by jiaxiaosong1002** [comment]
@exiawsh Hi, the expert model is Think2Drive, as stated in the paper. 

As for the PDM-Lite, yes, it is on the Bench2Drive test set.  The high score is because **they are expert model** with privileged inputs (GT boxes, map, etc).  Other baselines are e2e student model with only raw sensor inputs.
