### ISSUE TITLE
Ques about resume

### ISSUE THREAD

**Issue by starlighttt123** [Thinklab-SJTU/Bench2Drive#89]
hello，thanks  for your great work, but I'm currently facing some problems regarding the process of the resume even after having reviewed the relevant issues. My problem is that a process keep crashing after resume and since that I can't finish the whole eval process.
Could you please explain in detail what is the whole process of resume? Are they:
 1. find the crash id and comment it in xml 
 2. manually change the json file 
 3. re-run run_evaluation_multi_vad.sh
 Does it miss some other operation? Thanks for your reply！

**Comment by jayyoung0802** [comment]
For example,  if you comment one route in xml,  the total routes should be 16-1=15.
![image](https://github.com/user-attachments/assets/94536ec9-4c9e-455d-8558-83dafb54b617)

Manually change the total routes 16-->15
![image](https://github.com/user-attachments/assets/2bb3536e-46e5-42ed-8cb4-7917835d9071)

Before re-run run_evaluation_multi_vad.sh, please check [split_xml.py](https://github.com/Thinklab-SJTU/Bench2Drive/blob/main/leaderboard/scripts/run_evaluation_multi_vad.sh#L26). It **cannot be executed**, **otherwise the xml will be overwritten.**

Maybe some crash routes are continuous in xml file and may cause trouble for you. Just comment them out.

And we **publish our eval json** in [eval json](https://github.com/Thinklab-SJTU/Bench2DriveZoo/tree/uniad/vad/analysis), feel free to refer to it.
